### ISSUE TITLE
!!!!Urgent Help Need!!!!!. Error: "Failed to load application: 'module' object has no attribute IPluggableAuthenticationModules"

### ISSUE THREAD

**Issue by OceanTran999** [sosdow/RLHPot#4]
Hello, 
I use Python2.7.17, I run in virtual environment which is Ubuntu 18.04_64 bit, and these are my python libraries:
pybrain==0.3.3
twisted==15.1.0
cryptography==3.3.2
pyopenssl==18.0.0
numpy==1.16.6
scipy==1.2.3
pyasn1==0.5.0
MySQL-python==1.2.5
pycrypto==2.6.1
matplotlib==2.2.4

And I also installed "twistd" using command "sudo apt install python-core" and its version is 17.9.0. I installed it because when I first ran the ./start.sh it said "twistd command not found"

When I run ./start.sh and it has error message:
"""Starting KippoRLPot in background...Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "kippo.tac", line 25, in <module>
    from kippo.core import honeypot
  File "/home/duong/RLHPot/kippo/core/honeypot.py", line 728, in <module>
    class HoneypotPasswordChecker:
  File "/home/duong/RLHPot/kippo/core/honeypot.py", line 732, in HoneypotPasswordChecker
    credentials.IPluggableAuthenticationModules)
exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'

Failed to load application: 'module' object has no attribute 'IPluggableAuthenticationModules' """

Can someone help me to fix this error please, I'm very thankful

**Comment by OceanTran999** [comment]
Welp, I finally fixed it, the answer is you should run the code in terminal of VSCode instead of the terminal of Ubuntu/Debian
